# Generated by Django 4.0.5 on 2022-06-21 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('Client', 'Client'), ('Candidate', 'Candiate')], max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
