# Generated by Django 4.0.5 on 2022-06-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(max_length=255),
        ),
    ]
