# Generated by Django 4.0.5 on 2022-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_job_options_job_duration_alter_job_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, default='1 day', max_length=255),
        ),
    ]
