# Generated by Django 4.0.5 on 2022-06-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidate_gender',
            field=models.CharField(blank=True, default='Male or Female', max_length=300),
        ),
    ]
