# Generated by Django 4.0.5 on 2022-06-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobexperince'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobExperince',
            new_name='JobExperience',
        ),
    ]
