# Generated by Django 4.0.5 on 2022-06-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_jobexperince_jobexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobexperience'),
        ),
    ]
