# Generated by Django 4.0.5 on 2022-06-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_job_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexperience',
            old_name='type',
            new_name='level',
        ),
    ]
