# Generated by Django 4.0.5 on 2022-06-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_candidate_savedjobs_appliedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate', serialize=False, to='app.profile'),
        ),
    ]
