# Generated by Django 4.0.5 on 2022-06-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_candidate_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='about',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='created',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='role',
        ),
    ]
