# Generated by Django 4.0.5 on 2022-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_candidate_about_remove_candidate_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Candidate', 'Candidate')], max_length=200),
        ),
    ]
