# Generated by Django 4.0.5 on 2022-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_candidate_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank='True', null=True, to='app.candidate'),
        ),
    ]
