# Generated by Django 4.0.5 on 2022-06-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_job_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='app.job')),
            ],
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='date_posted',
            new_name='date_applied',
        ),
        migrations.DeleteModel(
            name='SavedJobs',
        ),
    ]
